name: Release (tag)

on:
  push:
    tags:
      - 'v*'   # e.g., v1.0.0, v0.2.4

permissions:
  contents: write   # required for creating GitHub Releases

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app (no publish)
        # Prevent electron-builder from trying to auto-publish during CI
        run: npx electron-builder --publish never

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          if-no-files-found: ignore
          path: |
            dist/*.AppImage
            dist/*.dmg
            dist/*.pkg
            dist/*.zip
            dist/*.exe
            dist/*.msi
            dist/*.deb
            dist/*.rpm
            dist/*.snap
            dist/*.yml
            dist/latest*.yml

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
